version = 3.11.2
runner.dialect = scala3
maxColumn = 100
docstrings.style = Asterisk
docstrings.wrap = yes
newlines.source = fold
rewrite.rules = [RedundantBraces, SortModifiers]
project.excludeFilters = ["target/.*"]
